CREATE TABLE users
(
    id INT NOT NULL AUTO_INCREMENT,
    lastName VARCHAR(255) DEFAULT '' NOT NULL,
    firstName VARCHAR(255) DEFAULT '' NOT NULL,
    email VARCHAR(255) DEFAULT '' NOT NULL,
    password VARCHAR(255) DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE contact
(
    userId VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) DEFAULT '' NOT NULL,
    firstName VARCHAR(255) DEFAULT '' NOT NULL,
    email VARCHAR(255) DEFAULT '' NOT NULL,
    address VARCHAR(255) DEFAULT '' NOT NULL,
    phone VARCHAR(255) DEFAULT '' NOT NULL,
    mobile VARCHAR(255) DEFAULT '' NOT NULL,
    comment VARCHAR(255) DEFAULT '' NOT NULL
);